description: "This page seeks to compile the notes of classes taught throughout all university sessions in terms of software development and applied mathematics."
email: "mundobit2022@gmail.com"
twitter: "https://twitter.com/camposjulca73"
